### ISSUE TITLE
telegram多用户的算法

### ISSUE THREAD

**Issue by JKme** [qwqdanchun/Pillager#10]
telegram 多用户算法如下，可以根据这个来计算多个用户的文件名
```
# coding: utf-8
import hashlib

def ToFilePart(val: int):
        result = str()
        for i in range(0, 0x10):
            v = val & 0xF
            if v < 0x0A:
                result += chr(ord("0") + v)
            else:
                result += chr(ord("A") + (v - 0x0A))
            val >>= 4
        return result


def md5_hex(d):
    md5 = hashlib.md5(d.encode("utf-8")).digest()
    return ToFilePart(int.from_bytes(md5, 'little'))

if __name__ == '__main__':
     print(md5_hex("data"))
     print(md5_hex("data#2"))
     print(md5_hex("data#3"))
```

**Comment by qwqdanchun** [comment]
目前已支持最多五个用户，暂时未遇到超过五个用户的情况



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月27日(周一) 上午9:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qwqdanchun/Pillager] telegram多用户的算法 (Issue #10)




 
telegram 多用户算法如下，可以根据这个来计算多个用户的文件名
 # coding: utf-8 import hashlib def ToFilePart(val: int):         result = str()         for i in range(0, 0x10):             v = val &amp; 0xF             if v < 0x0A:                 result += chr(ord("0") + v)             else:                 result += chr(ord("A") + (v - 0x0A))             val &gt;&gt;= 4         return result def md5_hex(d):     md5 = hashlib.md5(d.encode("utf-8")).digest()     return ToFilePart(int.from_bytes(md5, 'little')) if __name__ == '__main__':      print(md5_hex("data"))      print(md5_hex("data#2"))      print(md5_hex("data#3"))

**Comment by JKme** [comment]
Get
