### ISSUE TITLE
师傅师傅

### ISSUE THREAD

**Issue by UIWP0** [qwqdanchun/Pillager#12]
请问导出的这些default文件夹中的内容是源数据吧？保留到目录的用意是什么呢？
![image](https://github.com/qwqdanchun/Pillager/assets/32759429/9aff4da7-0b2e-4969-885b-8a104b489f8a)

![image](https://github.com/qwqdanchun/Pillager/assets/32759429/31935b71-faaf-455c-bd52-49095f2a1a73)

**Comment by qwqdanchun** [comment]
https://blog.qwqdanchun.com/Pillager_Forensics_2/

保存了插件的配置信息还有Local Storage，可以参考下文章内容
