### ISSUE TITLE
师傅，好强，donut

### ISSUE THREAD

**Issue by 1191569886** [qwqdanchun/Pillager#14]
师傅，好强，donut魔改后的代码能否分享下

**Comment by qwqdanchun** [comment]
![image](https://github.com/qwqdanchun/Pillager/assets/48477028/6f4c59f9-1265-4e1c-8761-9b4912da266e)
功能上只改了这里，为了兼容clr
其余都是精简了，去除了多余功能代码

**Comment by 1191569886** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
