### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by tiantnag** [qwqdanchun/Pillager#16]
我在cs中运行会直接让进程死掉，也没有对应的结果，直接上传exe运行exe会报错
未处理的异常:  System.UnauthorizedAccessException: 对路径“Qppv”的访问被拒绝。
   在 System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive)
   在 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive)
   在 Pillager.Program.Main(String[] args)

**Comment by qwqdanchun** [comment]
问题应该修复了
