### ISSUE TITLE
exe运行环境问题

### ISSUE THREAD

**Issue by 1n7erface** [qwqdanchun/Pillager#24]
师傅你好，exe在运行时存在.net版本问题。参考https://xz.aliyun.com/t/16823?time__1311=Gui%3DGI4UrdGNDQtiQ30Q5itDk8uxe5pD 中的"不同系统CLR环境兼容问题"

**Comment by qwqdanchun** [comment]
看了下，内容我很早的文章就提过了，并且已经在donut中处理过，https://blog.qwqdanchun.com/Pillager_Forensics_1/
