### ISSUE TITLE
获取压缩出错

### ISSUE THREAD

**Issue by 1rm** [qwqdanchun/Pillager#3]
获取不到谷歌浏览器的信息，并且会弹框报错
<img width="420" alt="屏幕截图 2023-10-30 143208" src="https://github.com/qwqdanchun/Pillager/assets/28972049/cec802d7-f9c9-48ec-a5b3-be20422db309">

更改了源码的保存路径虽然不报错但获取的谷歌浏览器内容还是为空

**Comment by qwqdanchun** [comment]
方便提供一下%localappdata%\Google\Chrome\User Data\Default文件夹的相关信息吗，正常使用过的chrome浏览器还没遇到过什么都提取不到，文件夹为空的情况

**Comment by 1rm** [comment]
https://cowtransfer.com/s/49893d6e944b4e 点击链接查看 [ User Data.zip ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 37q7l2 查看；

**Comment by qwqdanchun** [comment]
目录正常，方便调试看下吗

**Comment by 1rm** [comment]
使用SharpZipLib压缩库就没有这个问题了，原来那个开机第一次压缩就有问题但第二次就可以正常压缩

**Comment by qwqdanchun** [comment]
我晚点测试确认一下，不想使用第三方库，主要是因为体积太大😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月7日(周二) 中午11:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qwqdanchun/Pillager] 获取压缩出错 (Issue #3)




 
使用SharpZipLib压缩库就没有这个问题了，原来那个开机第一次压缩就有问题但第二次就可以正常压缩

**Comment by 1rm** [comment]
文件可以正常输出到目录，主要就是压缩那个环节有时候会压缩为空或者找不到目录，但我在另外一台机器测试就没有这种情况，估计是小概率事件

**Comment by qwqdanchun** [comment]
更换了一个较小体积的tar压缩方案，应该可以解决这个问题了 [#
commit/49ffc0af2ee9b1eb0c4cf6cf3eb69e9c8ff498cd](https://github.com/qwqdanchun/Pillager/commit/49ffc0af2ee9b1eb0c4cf6cf3eb69e9c8ff498cd)
