### ISSUE TITLE
默认chrome取用户1-5,额碰到大几十的是个问题！

### ISSUE THREAD

**Issue by iovejieba** [qwqdanchun/Pillager#4]
不知是否可用遍历方式呢....

**Comment by qwqdanchun** [comment]
目前我自己遇到的最多的是三个，就没有留更多余量



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月11日(周六) 中午1:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qwqdanchun/Pillager] 默认chrome取用户1-5,额碰到大几十的是个问题！ (Issue #4)




 
不知是否可用遍历方式呢....

**Comment by iovejieba** [comment]
> 目前我自己遇到的最多的是三个，就没有留更多余量
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月11日(周六) 中午1:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qwqdanchun/Pillager] 默认chrome取用户1-5,额碰到大几十的是个问题！ (Issue #4) 不知是否可用遍历方式呢.... — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
额 没事师傅 我用了最蛋疼的方式加到了99个

**Comment by qwqdanchun** [comment]
实际确实有这种情况的话，我明天改一下

**Comment by qwqdanchun** [comment]
已经修改了
[commit/6f4b99454c290205e887806306ab6c6ba8ba2e8b](https://github.com/qwqdanchun/Pillager/commit/6f4b99454c290205e887806306ab6c6ba8ba2e8b)

**Comment by iovejieba** [comment]
> 已经修改了 [commit/6f4b99454c290205e887806306ab6c6ba8ba2e8b](https://github.com/qwqdanchun/Pillager/commit/6f4b99454c290205e887806306ab6c6ba8ba2e8b)

师傅，变量遍历  貌似70 80这种大数字 它是没有遍历到的

**Comment by qwqdanchun** [comment]
目前是一直递增数字，直到文件不存在

如果没有遍历到，可能是删除过部分profile，导致中断？

**Comment by qwqdanchun** [comment]
目前遇到的最大的数量是多少

我还是写死一下吧

**Comment by iovejieba** [comment]
> 目前遇到的最大的数量是多少
> 
> 我还是写死一下吧

应该是递增断数了，导致遍历没有成功   目前来看还没有超过99的

**Comment by qwqdanchun** [comment]
改为了对100以下数字进行遍历

[commit/598920c9ed8ca3633335950e2e37df3d6589911](https://github.com/qwqdanchun/Pillager/commit/598920c9ed8ca3633335950e2e37df3d65899110)

**Comment by iovejieba** [comment]
> 改为了对100以下数字进行遍历
> 
> [commit/598920c9ed8ca3633335950e2e37df3d6589911](https://github.com/qwqdanchun/Pillager/commit/598920c9ed8ca3633335950e2e37df3d65899110)

好的师傅 我去跑个test看看

**Comment by iovejieba** [comment]
> 改为了对100以下数字进行遍历
> 
> [commit/598920c9ed8ca3633335950e2e37df3d6589911](https://github.com/qwqdanchun/Pillager/commit/598920c9ed8ca3633335950e2e37df3d65899110)

师傅 这次遍历没有问题了！

**Comment by qwqdanchun** [comment]
好的
