### ISSUE TITLE
师傅！

### ISSUE THREAD

**Issue by iovejieba** [qwqdanchun/Pillager#8]
在收集过程中，securecrt，FinalShell，winscp,tortoisesvn,这几个基本也属于高收集信息，不知道师傅是否有时间看适配一下

**Comment by qwqdanchun** [comment]
好的，会去看的，最近稍忙，下周我会把这几个处理下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月15日(周三) 晚上7:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [qwqdanchun/Pillager] 师傅！ (Issue #8)




 
在收集过程中，securecrt，finshall，winscp,tortoisesvn,这几个基本也属于高收集信息，不知道师傅是否有时间看适配一下

**Comment by iovejieba** [comment]
> 好的，会去看的，最近稍忙，下周我会把这几个处理下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月15日(周三) 晚上7:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [qwqdanchun/Pillager] 师傅！ (Issue #8) 在收集过程中，securecrt，finshall，winscp,tortoisesvn,这几个基本也属于高收集信息，不知道师傅是否有时间看适配一下 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好的，感谢！

**Comment by qwqdanchun** [comment]
已添加finshall和winscp，剩下两个可能稍晚一点添加

**Comment by iovejieba** [comment]
> 已添加finshall和winscp，剩下两个可能稍晚一点添加

好咧师傅辛苦！

**Comment by iovejieba** [comment]
另外师傅，在打洞收集的过程中额 可以考虑把cookie 导出为json 这样直接可用 相对方便很多

**Comment by qwqdanchun** [comment]
这个已经实现了，目前还在测试阶段，等我测试好会提交更新

**Comment by iovejieba** [comment]
> 这个已经实现了，目前还在测试阶段，等我测试好会提交更新

好咧 辛苦了！

**Comment by iovejieba** [comment]
> > 这个已经实现了，目前还在测试阶段，等我测试好会提交更新
> 
> 好咧 辛苦了！

师傅发现FinalShell并不能收集到相关信息！

**Comment by qwqdanchun** [comment]
FinalShell这个处理了一下，应该好了
des解密出了点遗漏

**Comment by iovejieba** [comment]
> FinalShell这个处理了一下，应该好了 des解密出了点遗漏

额...师傅本地测试 finalshell 好像依旧获取不到

**Comment by qwqdanchun** [comment]
方便调试一下看问题出在哪里吗，或者可以加我qq或微信(搜qwqdanchun就行)，然后我远程看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月10日(周日) 下午4:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qwqdanchun/Pillager] 师傅！ (Issue #8)




  
FinalShell这个处理了一下，应该好了 des解密出了点遗漏
  
额...师傅本地测试 finalshell 好像依旧获取不到

**Comment by iovejieba** [comment]
> 方便调试一下看问题出在哪里吗，或者可以加我qq或微信(搜qwqdanchun就行)，然后我远程看一下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年12月10日(周日) 下午4:10 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [qwqdanchun/Pillager] 师傅！ (Issue #8) FinalShell这个处理了一下，应该好了 des解密出了点遗漏 额...师傅本地测试 finalshell 好像依旧获取不到 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
我刚才esxi跑了个纯净机器测了下新版本的貌似是可以的，我本机的老版本貌似不行我去看看是不是新版老版路径问题，感谢师傅！

**Comment by qwqdanchun** [comment]
有老版本安装包可以发我一个，我去测试下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月10日(周日) 下午4:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qwqdanchun/Pillager] 师傅！ (Issue #8)




  
方便调试一下看问题出在哪里吗，或者可以加我qq或微信(搜qwqdanchun就行)，然后我远程看一下
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年12月10日(周日) 下午4:10 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [qwqdanchun/Pillager] 师傅！ (Issue #8) FinalShell这个处理了一下，应该好了 des解密出了点遗漏 额...师傅本地测试 finalshell 好像依旧获取不到 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
 我刚才esxi跑了个纯净机器测了下新版本的貌似是可以的，我本机的老版本貌似不行我去看看是不是新版老版路径问题，感谢师傅！

**Comment by iovejieba** [comment]
> 有老版本安装包可以发我一个，我去测试下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年12月10日(周日) 下午4:25 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [qwqdanchun/Pillager] 师傅！ (Issue #8) 方便调试一下看问题出在哪里吗，或者可以加我qq或微信(搜qwqdanchun就行)，然后我远程看一下 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年12月10日(周日) 下午4:10 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [qwqdanchun/Pillager] 师傅！ (Issue #8) FinalShell这个处理了一下，应该好了 des解密出了点遗漏 额...师傅本地测试 finalshell 好像依旧获取不到 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 我刚才esxi跑了个纯净机器测了下新版本的貌似是可以的，我本机的老版本貌似不行我去看看是不是新版老版路径问题，感谢师傅！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好咧师傅，我加您！ 刚才排查了下应该不是路径问题，路径一致情况诡异

**Comment by iovejieba** [comment]
> 有老版本安装包可以发我一个，我去测试下
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年12月10日(周日) 下午4:25 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [qwqdanchun/Pillager] 师傅！ (Issue #8) 方便调试一下看问题出在哪里吗，或者可以加我qq或微信(搜qwqdanchun就行)，然后我远程看一下 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2023年12月10日(周日) 下午4:10 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [qwqdanchun/Pillager] 师傅！ (Issue #8) FinalShell这个处理了一下，应该好了 des解密出了点遗漏 额...师傅本地测试 finalshell 好像依旧获取不到 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 我刚才esxi跑了个纯净机器测了下新版本的貌似是可以的，我本机的老版本貌似不行我去看看是不是新版老版路径问题，感谢师傅！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

又试了几个环境，应该单纯是我本地环境出现的诡异问题，其他机器暂时还未遇到，我在跑跑测试看看

**Comment by qwqdanchun** [comment]
好的👌🏻

**Comment by iovejieba** [comment]
师傅，.net看不太明白不过大体这次是如果chrome是未开启状态会导出ck为json吧？  如果chrome是开启占用状态就导出txt？ 就能看明白个大概....

**Comment by qwqdanchun** [comment]
目前都是导出为json的，会先尝试直接复制，发现无法复制文件时会查找进程并复制句柄去读取文件，只是改变了读取文件的方法，后面的处理过程没有变化

**Comment by iovejieba** [comment]
> 目前都是导出为json的，会先尝试直接复制，发现无法复制文件时会查找进程并复制句柄去读取文件，只是改变了读取文件的方法，后面的处理过程没有变化

师傅，无参数运行的话，这边测试导出的还是txt....

**Comment by qwqdanchun** [comment]
使用的最新版本吗，看下内容是不是json的

**Comment by iovejieba** [comment]
> 使用的最新版本吗，看下内容是不是json的

使用的是目前仓库里的自编译版本，格式依旧不是json的...

**Comment by qwqdanchun** [comment]
输出结果在%temp%/Pillager.tar.gz，结果方便截图看下吗

**Comment by iovejieba** [comment]
![image](https://github.com/qwqdanchun/Pillager/assets/12188252/464e143f-2319-45ea-8c80-bdb54e65d5af)


> 输出结果在%temp%/Pillager.tar.gz，结果方便截图看下吗

师傅您可以看下，这参数依旧应该还是老版本的样子

**Comment by qwqdanchun** [comment]
这就是json啊，可以直接导入Cookie-Editor等插件

**Comment by iovejieba** [comment]
> 这就是json啊，可以直接导入Cookie-Editor等插件

Cookie-Editor....貌似导入失败....额  那我在看看师傅...

**Comment by qwqdanchun** [comment]
修复了一点无法导入的bug，再试一下

**Comment by iovejieba** [comment]
> 修复了一点无法导入的bug，再试一下

ok...好咧师傅 我去跑测试

**Comment by iovejieba** [comment]
> 修复了一点无法导入的bug，再试一下

师傅，chrome未占用状态导出已经可以了！

**Comment by qwqdanchun** [comment]
> 在收集过程中，securecrt，FinalShell，winscp,tortoisesvn,这几个基本也属于高收集信息，不知道师傅是否有时间看适配一下

全部添加了
