### ISSUE TITLE
求师傅赐我神通

### ISSUE THREAD

**Issue by BigBlackChicken134** [qwqdanchun/Pillager#9]
师傅我在测试环境中使用cs4.4及之上版本时使用此插件时Pillager运行后直接超时读秒，使用4.2版本时在Server16，12上面执行均可但是在Win10上执行时也是直接读秒求师傅解答疑惑。小弟拜服，望师傅回复，顺颂时绥。

**Comment by qwqdanchun** [comment]
自己使用的4.5版本在常见系统上均无法复现此问题，未测试其他CS版本

**Comment by qwqdanchun** [comment]
方便的话，可以测试一下直接使用对应CLR版本的exe执行是否存在问题

**Comment by BigBlackChicken134** [comment]
> 方便的话，可以测试一下直接使用对应CLR版本的exe执行是否存在问题
感谢师傅
